version: '3.8'

services:
  blazor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${BLAZOR_APP_NAME}
    ports:
      - "${NGINX_PORT}:${BLAZOR_APP_PORT}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    environment:
      - BLAZOR_APP_NAME=${BLAZOR_APP_NAME}
      - BLAZOR_APP_PORT=${BLAZOR_APP_PORT}
